import type { TemplateDoc } from '../types/template';

export const createBistroTemplate = (): TemplateDoc => ({
  templateId: 'tpl-bistro-v1',
  templateName: 'Neighborhood Bistro',
  revision: 0,
  rootId: 'page-root',
  elements: {
    'page-root': {
      id: 'page-root',
      type: 'section',
      parentId: null,
      childIds: ['bistro-nav', 'welcome-section', 'story-section', 'menu-section', 'visit-section', 'reserve-section', 'basement-footer'],
      content: { base: {} },
      style: { base: { backgroundColor: '#fffbeb', color: '#292524' } },
    },
    'bistro-nav': {
      id: 'bistro-nav',
      type: 'nav',
      parentId: 'page-root',
      childIds: [],
      content: {
        base: {
          brand: 'Olive & Thyme',
          links: [
            { label: 'Menu', href: '#menu' },
            { label: 'Our story', href: '#story' },
            { label: 'Find us', href: '#visit' },
          ],
        },
      },
      style: {
        base: { backgroundColor: '#7c2d12', color: '#fef3c7', paddingX: 36, paddingY: 18 },
        overrides: { mobile: { paddingX: 14 } },
      },
    },
    'welcome-section': {
      id: 'welcome-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['welcome-heading', 'welcome-text', 'welcome-button'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#7c2d12', color: '#fef3c7', paddingX: 56, paddingY: 84 },
        overrides: { mobile: { paddingX: 18, paddingY: 56 } },
      },
    },
    'welcome-heading': {
      id: 'welcome-heading',
      type: 'heading',
      parentId: 'welcome-section',
      childIds: [],
      content: { base: { text: 'Slow food, warm room, good company.' } },
      style: {
        base: { fontSize: 44, fontWeight: 700, textAlign: 'center', lineHeight: 1.15, marginBottom: 16 },
        overrides: { tablet: { fontSize: 36 }, mobile: { fontSize: 28 } },
      },
    },
    'welcome-text': {
      id: 'welcome-text',
      type: 'text',
      parentId: 'welcome-section',
      childIds: [],
      content: {
        base: { text: 'A neighborhood bistro serving seasonal plates and natural wine from Wednesday to Sunday.' },
      },
      style: {
        base: { fontSize: 19, textAlign: 'center', lineHeight: 1.6, marginBottom: 30, color: '#fde68a' },
        overrides: { mobile: { fontSize: 16 } },
      },
    },
    'welcome-button': {
      id: 'welcome-button',
      type: 'button',
      parentId: 'welcome-section',
      childIds: [],
      content: { base: { label: 'Book a table', href: '#reserve' } },
      style: {
        base: {
          backgroundColor: '#fef3c7',
          color: '#7c2d12',
          fontSize: 17,
          fontWeight: 700,
          paddingX: 30,
          paddingY: 15,
          borderRadius: 999,
        },
      },
    },
    'story-section': {
      id: 'story-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['story-heading', 'story-text'],
      content: { base: {} },
      style: { base: { backgroundColor: '#fffbeb', paddingX: 72, paddingY: 56 } },
    },
    'story-heading': {
      id: 'story-heading',
      type: 'heading',
      parentId: 'story-section',
      childIds: [],
      content: { base: { text: 'From market morning to your table' } },
      style: {
        base: { fontSize: 28, fontWeight: 700, textAlign: 'center', marginBottom: 18, color: '#292524' },
        overrides: { mobile: { fontSize: 23 } },
      },
    },
    'story-text': {
      id: 'story-text',
      type: 'text',
      parentId: 'story-section',
      childIds: [],
      content: {
        base: { text: 'Chef Marta Vidal opened Olive & Thyme in 2019 after a decade of cooking across the Basque coast. The menu changes weekly with whatever the growers bring in — expect wood-fired vegetables, hand-made pasta and a short, honest wine list.' },
      },
      style: {
        base: { fontSize: 16, textAlign: 'center', lineHeight: 1.75, widthPercent: 78, color: '#57534e' },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'menu-section': {
      id: 'menu-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['menu-heading', 'dish-card-1', 'dish-card-2', 'dish-card-3'],
      content: { base: {} },
      style: { base: { backgroundColor: '#fef3c7', paddingX: 48, paddingY: 60 } },
    },
    'menu-heading': {
      id: 'menu-heading',
      type: 'heading',
      parentId: 'menu-section',
      childIds: [],
      content: { base: { text: 'This week’s highlights' } },
      style: {
        base: { fontSize: 30, fontWeight: 700, textAlign: 'center', marginBottom: 34, color: '#292524' },
        overrides: { mobile: { fontSize: 24 } },
      },
    },
    'dish-card-1': {
      id: 'dish-card-1',
      type: 'section',
      parentId: 'menu-section',
      childIds: ['dish-1-name', 'dish-1-detail'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#ffffff', borderRadius: 12, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'dish-1-name': {
      id: 'dish-1-name',
      type: 'heading',
      parentId: 'dish-card-1',
      childIds: [],
      content: { base: { text: 'Ember-roasted carrots · $12' } },
      style: { base: { fontSize: 17, fontWeight: 700, marginBottom: 8, color: '#292524' } },
    },
    'dish-1-detail': {
      id: 'dish-1-detail',
      type: 'text',
      parentId: 'dish-card-1',
      childIds: [],
      content: { base: { text: 'Whipped labneh, dukkah, cold-pressed olive oil from the market stall downstairs.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#57534e' } },
    },
    'dish-card-2': {
      id: 'dish-card-2',
      type: 'section',
      parentId: 'menu-section',
      childIds: ['dish-2-name', 'dish-2-detail'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#ffffff', borderRadius: 12, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'dish-2-name': {
      id: 'dish-2-name',
      type: 'heading',
      parentId: 'dish-card-2',
      childIds: [],
      content: { base: { text: 'Hand-cut tagliatelle · $21' } },
      style: { base: { fontSize: 17, fontWeight: 700, marginBottom: 8, color: '#292524' } },
    },
    'dish-2-detail': {
      id: 'dish-2-detail',
      type: 'text',
      parentId: 'dish-card-2',
      childIds: [],
      content: { base: { text: 'Slow beef ragù, twelve hours in the oven, finished with aged parmesan.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#57534e' } },
    },
    'dish-card-3': {
      id: 'dish-card-3',
      type: 'section',
      parentId: 'menu-section',
      childIds: ['dish-3-name', 'dish-3-detail'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#ffffff', borderRadius: 12, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'dish-3-name': {
      id: 'dish-3-name',
      type: 'heading',
      parentId: 'dish-card-3',
      childIds: [],
      content: { base: { text: 'Basque cheesecake · $10' } },
      style: { base: { fontSize: 17, fontWeight: 700, marginBottom: 8, color: '#292524' } },
    },
    'dish-3-detail': {
      id: 'dish-3-detail',
      type: 'text',
      parentId: 'dish-card-3',
      childIds: [],
      content: { base: { text: 'Burnt on purpose. Served with macerated plums when the season allows.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#57534e' } },
    },
    'visit-section': {
      id: 'visit-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['visit-heading', 'hours-list'],
      content: { base: {} },
      style: { base: { backgroundColor: '#fffbeb', paddingX: 64, paddingY: 52 } },
    },
    'visit-heading': {
      id: 'visit-heading',
      type: 'heading',
      parentId: 'visit-section',
      childIds: [],
      content: { base: { text: 'Find us' } },
      style: { base: { fontSize: 26, fontWeight: 700, textAlign: 'center', marginBottom: 20, color: '#292524' } },
    },
    'hours-list': {
      id: 'hours-list',
      type: 'list',
      parentId: 'visit-section',
      childIds: [],
      content: {
        base: {
          items: [
            '42 Larkspur Lane — corner of 9th',
            'Wednesday to Sunday, 5pm until late',
            'Walk-ins welcome; reservations for six or more',
          ],
        },
      },
      style: {
        base: { fontSize: 16, lineHeight: 2, widthPercent: 62, color: '#57534e' },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'reserve-section': {
      id: 'reserve-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['reserve-heading', 'reserve-button'],
      content: { base: {} },
      style: { base: { backgroundColor: '#292524', paddingX: 48, paddingY: 62 } },
    },
    'reserve-heading': {
      id: 'reserve-heading',
      type: 'heading',
      parentId: 'reserve-section',
      childIds: [],
      content: { base: { text: 'Save your seat by the window' } },
      style: {
        base: { fontSize: 28, fontWeight: 700, textAlign: 'center', marginBottom: 22, color: '#fef3c7' },
        overrides: { mobile: { fontSize: 22 } },
      },
    },
    'reserve-button': {
      id: 'reserve-button',
      type: 'button',
      parentId: 'reserve-section',
      childIds: [],
      content: { base: { label: 'Reserve now', href: 'tel:+15550142026' } },
      style: {
        base: {
          backgroundColor: '#f59e0b',
          color: '#292524',
          fontSize: 16,
          fontWeight: 700,
          paddingX: 30,
          paddingY: 15,
          borderRadius: 999,
        },
      },
    },
    'basement-footer': {
      id: 'basement-footer',
      type: 'section',
      parentId: 'page-root',
      childIds: ['footer-line'],
      content: { base: {} },
      style: { base: { backgroundColor: '#7c2d12', paddingX: 32, paddingY: 20 } },
    },
    'footer-line': {
      id: 'footer-line',
      type: 'text',
      parentId: 'basement-footer',
      childIds: [],
      content: { base: { text: 'Olive & Thyme · 42 Larkspur Lane · No tweets, just dinner.' } },
      style: { base: { fontSize: 13, textAlign: 'center', color: '#fde68a' } },
    },
  },
});
