import type { TemplateDoc } from '../types/template';

export const createBrutalistTemplate = (): TemplateDoc => ({
  templateId: 'tpl-noir-v1',
  templateName: 'Noir Signal',
  revision: 0,
  rootId: 'page-root',
  elements: {
    'page-root': {
      id: 'page-root',
      type: 'section',
      parentId: null,
      childIds: ['noir-nav', 'hero-section', 'spec-section', 'manifest-section', 'schedule-section', 'register-section', 'noir-footer'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0A0A0B', color: '#F5F5F0' } },
    },
    'noir-nav': {
      id: 'noir-nav',
      type: 'nav',
      parentId: 'page-root',
      childIds: [],
      content: {
        base: {
          brand: 'SIGNAL — NO.04',
          links: [
            { label: 'System', href: '#system' },
            { label: 'Schedule', href: '#schedule' },
            { label: 'Register', href: '#register' },
          ],
        },
      },
      style: {
        base: { backgroundColor: '#0A0A0B', color: '#F5F5F0', paddingX: 32, paddingY: 18 },
        overrides: { mobile: { paddingX: 14 } },
      },
    },
    'hero-section': {
      id: 'hero-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['hero-kicker', 'hero-heading', 'hero-subtext', 'hero-cta'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#0A0A0B', color: '#F5F5F0', paddingX: 56, paddingY: 80 },
        overrides: { mobile: { paddingX: 18, paddingY: 52 } },
      },
    },
    'hero-kicker': {
      id: 'hero-kicker',
      type: 'text',
      parentId: 'hero-section',
      childIds: [],
      content: { base: { text: 'SYSTEM / 2026 — ISSUE 04 / BERLIN + ONLINE' } },
      style: {
        base: {
          fontSize: 12,
          fontWeight: 700,
          textAlign: 'center',
          color: '#EAB308',
          marginBottom: 16,
          lineHeight: 1.4,
        },
      },
    },
    'hero-heading': {
      id: 'hero-heading',
      type: 'heading',
      parentId: 'hero-section',
      childIds: [],
      content: { base: { text: 'INDUSTRIAL TYPE SYSTEM' } },
      style: {
        base: { fontSize: 68, fontWeight: 800, textAlign: 'center', lineHeight: 0.95, marginBottom: 18, color: '#F5F5F0' },
        overrides: { tablet: { fontSize: 44 }, mobile: { fontSize: 32 } },
      },
    },
    'hero-subtext': {
      id: 'hero-subtext',
      type: 'text',
      parentId: 'hero-section',
      childIds: [],
      content: { base: { text: 'A two-day inspection of how type behaves under pressure — mono, grid, and concrete. Bring calipers.' } },
      style: {
        base: { fontSize: 18, textAlign: 'center', lineHeight: 1.6, marginBottom: 28, color: '#A1A1AA' },
        overrides: { mobile: { fontSize: 15 } },
      },
    },
    'hero-cta': {
      id: 'hero-cta',
      type: 'button',
      parentId: 'hero-section',
      childIds: [],
      content: { base: { label: 'Secure a seat — $240', href: '#register' } },
      style: {
        base: {
          backgroundColor: '#EAB308',
          color: '#0A0A0B',
          fontSize: 16,
          fontWeight: 800,
          paddingX: 30,
          paddingY: 15,
          borderRadius: 0,
        },
      },
    },
    'spec-section': {
      id: 'spec-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['spec-heading', 'spec-card-1', 'spec-card-2', 'spec-card-3'],
      content: { base: {} },
      style: { base: { backgroundColor: '#F5F5F0', paddingX: 40, paddingY: 56 } },
    },
    'spec-heading': {
      id: 'spec-heading',
      type: 'heading',
      parentId: 'spec-section',
      childIds: [],
      content: { base: { text: 'THREE TOLERANCES' } },
      style: {
        base: { fontSize: 30, fontWeight: 800, textAlign: 'center', marginBottom: 32, color: '#0A0A0B', lineHeight: 1.1 },
        overrides: { mobile: { fontSize: 22 } },
      },
    },
    'spec-card-1': {
      id: 'spec-card-1',
      type: 'section',
      parentId: 'spec-section',
      childIds: ['spec-1-label', 'spec-1-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#FFFFFF', borderRadius: 0, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'spec-1-label': {
      id: 'spec-1-label',
      type: 'heading',
      parentId: 'spec-card-1',
      childIds: [],
      content: { base: { text: '01 — STROKE' } },
      style: { base: { fontSize: 16, fontWeight: 800, marginBottom: 10, color: '#0A0A0B' } },
    },
    'spec-1-text': {
      id: 'spec-1-text',
      type: 'text',
      parentId: 'spec-card-1',
      childIds: [],
      content: { base: { text: 'Weight is tolerance. How thin before it breaks at 6pt on newsprint?' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#52525B' } },
    },
    'spec-card-2': {
      id: 'spec-card-2',
      type: 'section',
      parentId: 'spec-section',
      childIds: ['spec-2-label', 'spec-2-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#0A0A0B', borderRadius: 0, paddingX: 22, paddingY: 22, widthPercent: 33, color: '#F5F5F0' },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'spec-2-label': {
      id: 'spec-2-label',
      type: 'heading',
      parentId: 'spec-card-2',
      childIds: [],
      content: { base: { text: '02 — GRID' } },
      style: { base: { fontSize: 16, fontWeight: 800, marginBottom: 10, color: '#F5F5F0' } },
    },
    'spec-2-text': {
      id: 'spec-2-text',
      type: 'text',
      parentId: 'spec-card-2',
      childIds: [],
      content: { base: { text: 'The grid is not decoration. 8 columns, 16 gaps, no exceptions — even for logos.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#A1A1AA' } },
    },
    'spec-card-3': {
      id: 'spec-card-3',
      type: 'section',
      parentId: 'spec-section',
      childIds: ['spec-3-label', 'spec-3-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#EAB308', borderRadius: 0, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'spec-3-label': {
      id: 'spec-3-label',
      type: 'heading',
      parentId: 'spec-card-3',
      childIds: [],
      content: { base: { text: '03 — INK' } },
      style: { base: { fontSize: 16, fontWeight: 800, marginBottom: 10, color: '#0A0A0B' } },
    },
    'spec-3-text': {
      id: 'spec-3-text',
      type: 'text',
      parentId: 'spec-card-3',
      childIds: [],
      content: { base: { text: 'Test on the worst stock you can find. If it survives, it is a system.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#422006' } },
    },
    'manifest-section': {
      id: 'manifest-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['manifest-quote', 'manifest-meta'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0A0A0B', paddingX: 64, paddingY: 56 } },
    },
    'manifest-quote': {
      id: 'manifest-quote',
      type: 'text',
      parentId: 'manifest-section',
      childIds: [],
      content: { base: { text: '“If you need decoration, your grid has failed.”' } },
      style: {
        base: { fontSize: 24, textAlign: 'center', lineHeight: 1.45, marginBottom: 12, color: '#EAB308' },
        overrides: { mobile: { fontSize: 18 } },
      },
    },
    'manifest-meta': {
      id: 'manifest-meta',
      type: 'text',
      parentId: 'manifest-section',
      childIds: [],
      content: { base: { text: '— Signal Specification v4.1, p. 09' } },
      style: { base: { fontSize: 13, fontWeight: 600, textAlign: 'center', color: '#71717A' } },
    },
    'schedule-section': {
      id: 'schedule-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['schedule-heading', 'schedule-list'],
      content: { base: {} },
      style: { base: { backgroundColor: '#F5F5F0', paddingX: 64, paddingY: 52 } },
    },
    'schedule-heading': {
      id: 'schedule-heading',
      type: 'heading',
      parentId: 'schedule-section',
      childIds: [],
      content: { base: { text: 'SCHEDULE — DAY ONE' } },
      style: {
        base: { fontSize: 22, fontWeight: 800, textAlign: 'center', marginBottom: 20, color: '#0A0A0B' },
        overrides: { mobile: { fontSize: 18 } },
      },
    },
    'schedule-list': {
      id: 'schedule-list',
      type: 'list',
      parentId: 'schedule-section',
      childIds: [],
      content: {
        base: {
          items: [
            '09:00 — Calibration: mono at 5pt, 6pt, 7pt (live print)',
            '11:00 — Grid critique: your posters vs. the spec',
            '13:30 — Concrete: type poured, not printed',
            '16:00 — Tolerance test: newsprint wash',
          ],
        },
        overrides: { mobile: { items: ['09:00 — Calibration', '11:00 — Grid critique', '13:30 — Concrete'] } },
      },
      style: {
        base: { fontSize: 15, lineHeight: 1.9, widthPercent: 72, color: '#27272A' },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'register-section': {
      id: 'register-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['register-heading', 'register-button'],
      content: { base: {} },
      style: { base: { backgroundColor: '#EAB308', paddingX: 48, paddingY: 64 } },
    },
    'register-heading': {
      id: 'register-heading',
      type: 'heading',
      parentId: 'register-section',
      childIds: [],
      content: { base: { text: 'LAST 40 SEATS AT WORKSHOP RATE' } },
      style: {
        base: { fontSize: 28, fontWeight: 800, textAlign: 'center', marginBottom: 22, color: '#0A0A0B', lineHeight: 1.15 },
        overrides: { mobile: { fontSize: 20 } },
      },
    },
    'register-button': {
      id: 'register-button',
      type: 'button',
      parentId: 'register-section',
      childIds: [],
      content: { base: { label: 'Register now — $240', href: '#register' } },
      style: {
        base: {
          backgroundColor: '#0A0A0B',
          color: '#F5F5F0',
          fontSize: 16,
          fontWeight: 800,
          paddingX: 30,
          paddingY: 15,
          borderRadius: 0,
        },
      },
    },
    'noir-footer': {
      id: 'noir-footer',
      type: 'section',
      parentId: 'page-root',
      childIds: ['footer-note'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0A0A0B', paddingX: 32, paddingY: 20 } },
    },
    'footer-note': {
      id: 'footer-note',
      type: 'text',
      parentId: 'noir-footer',
      childIds: [],
      content: { base: { text: '© 2026 Signal Systems. Set in JetBrains Mono. 52.4862°N, 13.4120°E — no livestream.' } },
      style: { base: { fontSize: 12, textAlign: 'center', color: '#71717A' } },
    },
  },
});
