import type { TemplateDoc } from '../types/template';

export const createEditorialTemplate = (): TemplateDoc => ({
  templateId: 'tpl-editorial-v1',
  templateName: 'Editorial Atelier',
  revision: 0,
  rootId: 'page-root',
  elements: {
    'page-root': {
      id: 'page-root',
      type: 'section',
      parentId: null,
      childIds: [
        'atelier-nav',
        'masthead-section',
        'feature-grid',
        'archive-section',
        'letter-section',
        'colophon-footer',
      ],
      content: { base: {} },
      style: { base: { backgroundColor: '#FFFBF5', color: '#1A1A1E' } },
    },
    'atelier-nav': {
      id: 'atelier-nav',
      type: 'nav',
      parentId: 'page-root',
      childIds: [],
      content: {
        base: {
          brand: 'ATELIER — 06',
          links: [
            { label: 'Archive', href: '#archive' },
            { label: 'Index', href: '#index' },
            { label: 'Subscribe', href: '#subscribe' },
          ],
        },
      },
      style: {
        base: { backgroundColor: '#1A1A1E', color: '#FFFBF5', paddingX: 40, paddingY: 18 },
        overrides: { mobile: { paddingX: 16 } },
      },
    },
    'masthead-section': {
      id: 'masthead-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['masthead-eyebrow', 'masthead-heading', 'masthead-deck', 'masthead-cta'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#FFFBF5', color: '#1A1A1E', paddingX: 64, paddingY: 72 },
        overrides: { mobile: { paddingX: 20, paddingY: 48 } },
      },
    },
    'masthead-eyebrow': {
      id: 'masthead-eyebrow',
      type: 'text',
      parentId: 'masthead-section',
      childIds: [],
      content: { base: { text: 'ISSUE 06 — SPRING 2026 / A SLOW JOURNAL' } },
      style: {
        base: {
          fontSize: 12,
          fontWeight: 600,
          textAlign: 'center',
          color: '#8A9A8B',
          marginBottom: 12,
          lineHeight: 1.4,
        },
      },
    },
    'masthead-heading': {
      id: 'masthead-heading',
      type: 'heading',
      parentId: 'masthead-section',
      childIds: [],
      content: { base: { text: 'Design for the long stay.' } },
      style: {
        base: {
          fontSize: 54,
          fontWeight: 800,
          textAlign: 'center',
          lineHeight: 1.05,
          marginBottom: 16,
          color: '#1A1A1E',
        },
        overrides: { tablet: { fontSize: 38 }, mobile: { fontSize: 28 } },
      },
    },
    'masthead-deck': {
      id: 'masthead-deck',
      type: 'text',
      parentId: 'masthead-section',
      childIds: [],
      content: {
        base: { text: 'Objects, rooms, and the tools we keep for decades. No trends, just notes from workshops that got it right.' },
      },
      style: {
        base: { fontSize: 19, textAlign: 'center', lineHeight: 1.6, marginBottom: 28, color: '#57534E' },
        overrides: { mobile: { fontSize: 16 } },
      },
    },
    'masthead-cta': {
      id: 'masthead-cta',
      type: 'button',
      parentId: 'masthead-section',
      childIds: [],
      content: { base: { label: 'Read the issue — $8', href: '#issue' } },
      style: {
        base: {
          backgroundColor: '#C45A3C',
          color: '#FFFBF5',
          fontSize: 16,
          fontWeight: 700,
          paddingX: 28,
          paddingY: 14,
          borderRadius: 10,
        },
      },
    },
    'feature-grid': {
      id: 'feature-grid',
      type: 'section',
      parentId: 'page-root',
      childIds: ['feature-hero-card', 'feature-side-card-1', 'feature-side-card-2'],
      content: { base: {} },
      style: { base: { backgroundColor: '#FFFBF5', paddingX: 48, paddingY: 40 } },
    },
    'feature-hero-card': {
      id: 'feature-hero-card',
      type: 'section',
      parentId: 'feature-grid',
      childIds: ['hero-image', 'hero-title', 'hero-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#FFFFFF', borderRadius: 16, paddingX: 24, paddingY: 24, widthPercent: 58 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'hero-image': {
      id: 'hero-image',
      type: 'image',
      parentId: 'feature-hero-card',
      childIds: [],
      content: {
        base: {
          src: 'https://picsum.photos/seed/atelier-hero/800/520',
          alt: 'Nagano workshop interior with wooden chairs',
        },
      },
      style: {
        base: { widthPercent: 100, height: 220, borderRadius: 12, marginBottom: 16 },
      },
    },
    'hero-title': {
      id: 'hero-title',
      type: 'heading',
      parentId: 'feature-hero-card',
      childIds: [],
      content: { base: { text: 'The chair that outlived its house' } },
      style: { base: { fontSize: 22, fontWeight: 700, marginBottom: 8, color: '#1A1A1E', lineHeight: 1.25 } },
    },
    'hero-text': {
      id: 'hero-text',
      type: 'text',
      parentId: 'feature-hero-card',
      childIds: [],
      content: { base: { text: 'In Nagano, one workshop has made the same frame since 1972. We visited for a week and left with splinters.' } },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#57534E' } },
    },
    'feature-side-card-1': {
      id: 'feature-side-card-1',
      type: 'section',
      parentId: 'feature-grid',
      childIds: ['side-1-title', 'side-1-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#EDE8E1', borderRadius: 16, paddingX: 24, paddingY: 24, widthPercent: 38 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'side-1-title': {
      id: 'side-1-title',
      type: 'heading',
      parentId: 'feature-side-card-1',
      childIds: [],
      content: { base: { text: 'A handbook for repair' } },
      style: { base: { fontSize: 19, fontWeight: 700, marginBottom: 10, color: '#1A1A1E' } },
    },
    'side-1-text': {
      id: 'side-1-text',
      type: 'text',
      parentId: 'feature-side-card-1',
      childIds: [],
      content: { base: { text: 'Why we annotated every screw in the catalogue. So you can fix it in 20 years without calling us.' } },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#57534E' } },
    },
    'feature-side-card-2': {
      id: 'feature-side-card-2',
      type: 'section',
      parentId: 'feature-grid',
      childIds: ['side-2-title', 'side-2-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#1A1A1E', borderRadius: 16, paddingX: 24, paddingY: 24, widthPercent: 38, color: '#FFFBF5' },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'side-2-title': {
      id: 'side-2-title',
      type: 'heading',
      parentId: 'feature-side-card-2',
      childIds: [],
      content: { base: { text: 'The library of spare parts' } },
      style: { base: { fontSize: 19, fontWeight: 700, marginBottom: 10, color: '#FFFBF5' } },
    },
    'side-2-text': {
      id: 'side-2-text',
      type: 'text',
      parentId: 'feature-side-card-2',
      childIds: [],
      content: { base: { text: 'Every back issue, paper swatch and failed glaze lives here. Come borrow, not buy.' } },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#D6D3D1' } },
    },
    'archive-section': {
      id: 'archive-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['archive-heading', 'archive-list'],
      content: { base: {} },
      style: { base: { backgroundColor: '#EDE8E1', paddingX: 64, paddingY: 52 } },
    },
    'archive-heading': {
      id: 'archive-heading',
      type: 'heading',
      parentId: 'archive-section',
      childIds: [],
      content: { base: { text: 'From the archive' } },
      style: {
        base: { fontSize: 26, fontWeight: 700, textAlign: 'center', marginBottom: 22, color: '#1A1A1E' },
        overrides: { mobile: { fontSize: 22 } },
      },
    },
    'archive-list': {
      id: 'archive-list',
      type: 'list',
      parentId: 'archive-section',
      childIds: [],
      content: {
        base: {
          items: [
            '05 — The kiln that never cooled (Kyoto, 48 pages)',
            '04 — How to wrap a parcel so it survives the post',
            '03 — Twelve door handles and why they matter',
            '02 — A year of mending: darning as drawing',
          ],
        },
        overrides: { mobile: { items: ['05 — The kiln (Kyoto)', '04 — Wrapping parcels', '03 — Door handles'] } },
      },
      style: {
        base: { fontSize: 15, lineHeight: 1.9, widthPercent: 68, color: '#44403C' },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'letter-section': {
      id: 'letter-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['letter-heading', 'letter-text', 'letter-button'],
      content: { base: {} },
      style: { base: { backgroundColor: '#C45A3C', paddingX: 48, paddingY: 60 } },
    },
    'letter-heading': {
      id: 'letter-heading',
      type: 'heading',
      parentId: 'letter-section',
      childIds: [],
      content: { base: { text: 'Get the print edition once a season' } },
      style: {
        base: { fontSize: 28, fontWeight: 700, textAlign: 'center', marginBottom: 14, color: '#FFFBF5' },
        overrides: { mobile: { fontSize: 22 } },
      },
    },
    'letter-text': {
      id: 'letter-text',
      type: 'text',
      parentId: 'letter-section',
      childIds: [],
      content: { base: { text: 'Four issues, no ads, posted flat. Subscribers also get the spare-parts library card.' } },
      style: { base: { fontSize: 16, textAlign: 'center', lineHeight: 1.6, marginBottom: 22, color: '#FDE8E1' } },
    },
    'letter-button': {
      id: 'letter-button',
      type: 'button',
      parentId: 'letter-section',
      childIds: [],
      content: { base: { label: 'Subscribe — $48 / year', href: '#subscribe' } },
      style: {
        base: {
          backgroundColor: '#1A1A1E',
          color: '#FFFBF5',
          fontSize: 16,
          fontWeight: 700,
          paddingX: 28,
          paddingY: 14,
          borderRadius: 999,
        },
      },
    },
    'colophon-footer': {
      id: 'colophon-footer',
      type: 'section',
      parentId: 'page-root',
      childIds: ['colophon-text'],
      content: { base: {} },
      style: { base: { backgroundColor: '#1A1A1E', paddingX: 32, paddingY: 20 } },
    },
    'colophon-text': {
      id: 'colophon-text',
      type: 'text',
      parentId: 'colophon-footer',
      childIds: [],
      content: { base: { text: '© 2026 Atelier Journal. Printed on Munken, set in Editorial Grotesk. No tracking, no pop-ups.' } },
      style: { base: { fontSize: 12, textAlign: 'center', color: '#8A9A8B' } },
    },
  },
});
