import type { TemplateDoc } from '../types/template';

export const createHorizonTemplate = (): TemplateDoc => ({
  templateId: 'tpl-horizon-v1',
  templateName: 'Horizon Retreat',
  revision: 0,
  rootId: 'page-root',
  elements: {
    'page-root': {
      id: 'page-root',
      type: 'section',
      parentId: null,
      childIds: ['horizon-nav', 'hero-section', 'stay-section', 'story-section', 'voices-section', 'book-section', 'horizon-footer'],
      content: { base: {} },
      style: { base: { backgroundColor: '#FDEDDC', color: '#1B0F2E' } },
    },
    'horizon-nav': {
      id: 'horizon-nav',
      type: 'nav',
      parentId: 'page-root',
      childIds: [],
      content: {
        base: {
          brand: 'HORIZON',
          links: [
            { label: 'Stay', href: '#stay' },
            { label: 'Journal', href: '#journal' },
            { label: 'Book', href: '#book' },
          ],
        },
      },
      style: {
        base: { backgroundColor: '#1B0F2E', color: '#FDEDDC', paddingX: 40, paddingY: 18 },
        overrides: { mobile: { paddingX: 16 } },
      },
    },
    'hero-section': {
      id: 'hero-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['hero-image', 'hero-heading', 'hero-text', 'hero-button'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#1B0F2E', color: '#FDEDDC', paddingX: 48, paddingY: 72 },
        overrides: { mobile: { paddingX: 20, paddingY: 48 } },
      },
    },
    'hero-image': {
      id: 'hero-image',
      type: 'image',
      parentId: 'hero-section',
      childIds: [],
      content: {
        base: {
          src: 'https://picsum.photos/seed/horizon-hero/1200/720',
          alt: 'Twilight view over black-water pool and sea',
        },
      },
      style: { base: { widthPercent: 100, height: 320, borderRadius: 20, marginBottom: 24 } },
    },
    'hero-heading': {
      id: 'hero-heading',
      type: 'heading',
      parentId: 'hero-section',
      childIds: [],
      content: { base: { text: 'A house on the edge of the night.' } },
      style: {
        base: { fontSize: 48, fontWeight: 800, textAlign: 'center', lineHeight: 1.1, marginBottom: 16, color: '#FDEDDC' },
        overrides: { tablet: { fontSize: 38 }, mobile: { fontSize: 28 } },
      },
    },
    'hero-text': {
      id: 'hero-text',
      type: 'text',
      parentId: 'hero-section',
      childIds: [],
      content: { base: { text: 'Three cabins, open kitchen, black-water pool. Twenty minutes from the ferry, a world away on the Azores.' } },
      style: {
        base: { fontSize: 18, textAlign: 'center', lineHeight: 1.6, marginBottom: 28, color: '#DDD6FE' },
        overrides: { mobile: { fontSize: 15 } },
      },
    },
    'hero-button': {
      id: 'hero-button',
      type: 'button',
      parentId: 'hero-section',
      childIds: [],
      content: { base: { label: 'Check availability', href: '#book' } },
      style: {
        base: {
          backgroundColor: '#FF6B6B',
          color: '#FFFFFF',
          fontSize: 17,
          fontWeight: 700,
          paddingX: 32,
          paddingY: 15,
          borderRadius: 999,
        },
      },
    },
    'stay-section': {
      id: 'stay-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['stay-heading', 'stay-card-1', 'stay-card-2', 'stay-card-3'],
      content: { base: {} },
      style: { base: { backgroundColor: '#FDEDDC', paddingX: 48, paddingY: 60 } },
    },
    'stay-heading': {
      id: 'stay-heading',
      type: 'heading',
      parentId: 'stay-section',
      childIds: [],
      content: { base: { text: 'Stay a while' } },
      style: {
        base: { fontSize: 32, fontWeight: 800, textAlign: 'center', marginBottom: 34, color: '#1B0F2E' },
        overrides: { mobile: { fontSize: 24 } },
      },
    },
    'stay-card-1': {
      id: 'stay-card-1',
      type: 'section',
      parentId: 'stay-section',
      childIds: ['stay-1-image', 'stay-1-title', 'stay-1-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#FFFFFF', borderRadius: 20, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'stay-1-image': {
      id: 'stay-1-image',
      type: 'image',
      parentId: 'stay-card-1',
      childIds: [],
      content: {
        base: {
          src: 'https://picsum.photos/seed/horizon-cove/600/420',
          alt: 'Glass cabin interior with hinoki bath',
        },
      },
      style: { base: { widthPercent: 100, height: 160, borderRadius: 16, marginBottom: 14 } },
    },
    'stay-1-title': {
      id: 'stay-1-title',
      type: 'heading',
      parentId: 'stay-card-1',
      childIds: [],
      content: { base: { text: 'The Cove · from €240' } },
      style: { base: { fontSize: 18, fontWeight: 700, marginBottom: 8, color: '#1B0F2E' } },
    },
    'stay-1-text': {
      id: 'stay-1-text',
      type: 'text',
      parentId: 'stay-card-1',
      childIds: [],
      content: { base: { text: 'Floor-to-ceiling glass, hinoki bath, wood stove. The sea is your white noise.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#57534E' } },
    },
    'stay-card-2': {
      id: 'stay-card-2',
      type: 'section',
      parentId: 'stay-section',
      childIds: ['stay-2-image', 'stay-2-title', 'stay-2-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#FFFFFF', borderRadius: 20, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'stay-2-image': {
      id: 'stay-2-image',
      type: 'image',
      parentId: 'stay-card-2',
      childIds: [],
      content: {
        base: {
          src: 'https://picsum.photos/seed/horizon-dune/600/420',
          alt: 'Dune cabin at golden hour',
        },
      },
      style: { base: { widthPercent: 100, height: 160, borderRadius: 16, marginBottom: 14 } },
    },
    'stay-2-title': {
      id: 'stay-2-title',
      type: 'heading',
      parentId: 'stay-card-2',
      childIds: [],
      content: { base: { text: 'The Dune · from €280' } },
      style: { base: { fontSize: 18, fontWeight: 700, marginBottom: 8, color: '#1B0F2E' } },
    },
    'stay-2-text': {
      id: 'stay-2-text',
      type: 'text',
      parentId: 'stay-card-2',
      childIds: [],
      content: { base: { text: 'Set among pines, private deck, outdoor shower. We left the grass to the wind.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#57534E' } },
    },
    'stay-card-3': {
      id: 'stay-card-3',
      type: 'section',
      parentId: 'stay-section',
      childIds: ['stay-3-image', 'stay-3-title', 'stay-3-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#1B0F2E', borderRadius: 20, paddingX: 22, paddingY: 22, widthPercent: 33, color: '#FDEDDC' },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'stay-3-image': {
      id: 'stay-3-image',
      type: 'image',
      parentId: 'stay-card-3',
      childIds: [],
      content: {
        base: {
          src: 'https://picsum.photos/seed/horizon-pines/600/420',
          alt: 'Pines and twilight sky over retreat',
        },
      },
      style: { base: { widthPercent: 100, height: 160, borderRadius: 16, marginBottom: 14 } },
    },
    'stay-3-title': {
      id: 'stay-3-title',
      type: 'heading',
      parentId: 'stay-card-3',
      childIds: [],
      content: { base: { text: 'The Pines · from €320' } },
      style: { base: { fontSize: 18, fontWeight: 700, marginBottom: 8, color: '#FDEDDC' } },
    },
    'stay-3-text': {
      id: 'stay-3-text',
      type: 'text',
      parentId: 'stay-card-3',
      childIds: [],
      content: { base: { text: 'Two bedrooms, long table for eight, vinyl and a kitchen that begs you to cook.' } },
      style: { base: { fontSize: 14, lineHeight: 1.6, color: '#DDD6FE' } },
    },
    'story-section': {
      id: 'story-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['story-heading', 'story-text'],
      content: { base: {} },
      style: { base: { backgroundColor: '#1B0F2E', paddingX: 72, paddingY: 56 } },
    },
    'story-heading': {
      id: 'story-heading',
      type: 'heading',
      parentId: 'story-section',
      childIds: [],
      content: { base: { text: 'Built around the light' } },
      style: { base: { fontSize: 28, fontWeight: 700, textAlign: 'center', marginBottom: 16, color: '#FDEDDC' } },
    },
    'story-text': {
      id: 'story-text',
      type: 'text',
      parentId: 'story-section',
      childIds: [],
      content: {
        base: { text: 'Every room faces west. We planted no lawn — just dune grass and pines the wind already owned. Solar, cistern water, and a shop that sells only what keeps.' },
      },
      style: {
        base: { fontSize: 16, textAlign: 'center', lineHeight: 1.75, widthPercent: 74, color: '#DDD6FE' },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'voices-section': {
      id: 'voices-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['voices-heading', 'voices-quote', 'voices-attr'],
      content: { base: {} },
      style: { base: { backgroundColor: '#FFFFFF', paddingX: 72, paddingY: 52 } },
    },
    'voices-heading': {
      id: 'voices-heading',
      type: 'heading',
      parentId: 'voices-section',
      childIds: [],
      content: { base: { text: 'Before you arrive' } },
      style: { base: { fontSize: 22, fontWeight: 700, textAlign: 'center', marginBottom: 18, color: '#1B0F2E' } },
    },
    'voices-quote': {
      id: 'voices-quote',
      type: 'text',
      parentId: 'voices-section',
      childIds: [],
      content: { base: { text: '“We came for two nights and stayed five. The sea does half the work — the house does the rest.”' } },
      style: {
        base: { fontSize: 20, textAlign: 'center', lineHeight: 1.55, marginBottom: 10, color: '#1B0F2E' },
        overrides: { mobile: { fontSize: 16 } },
      },
    },
    'voices-attr': {
      id: 'voices-attr',
      type: 'text',
      parentId: 'voices-section',
      childIds: [],
      content: { base: { text: '— Mika & Jon, Berlin · stayed in The Cove, March' } },
      style: { base: { fontSize: 13, fontWeight: 600, textAlign: 'center', color: '#78716C' } },
    },
    'book-section': {
      id: 'book-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['book-heading', 'book-button'],
      content: { base: {} },
      style: { base: { backgroundColor: '#FF6B6B', paddingX: 48, paddingY: 64 } },
    },
    'book-heading': {
      id: 'book-heading',
      type: 'heading',
      parentId: 'book-section',
      childIds: [],
      content: { base: { text: 'Nights are quiet here' } },
      style: {
        base: { fontSize: 30, fontWeight: 800, textAlign: 'center', marginBottom: 22, color: '#FFFFFF' },
        overrides: { mobile: { fontSize: 22 } },
      },
    },
    'book-button': {
      id: 'book-button',
      type: 'button',
      parentId: 'book-section',
      childIds: [],
      content: { base: { label: 'Book — from €240 / night', href: '#book' } },
      style: {
        base: {
          backgroundColor: '#1B0F2E',
          color: '#FFFFFF',
          fontSize: 16,
          fontWeight: 700,
          paddingX: 30,
          paddingY: 15,
          borderRadius: 999,
        },
      },
    },
    'horizon-footer': {
      id: 'horizon-footer',
      type: 'section',
      parentId: 'page-root',
      childIds: ['footer-note'],
      content: { base: {} },
      style: { base: { backgroundColor: '#1B0F2E', paddingX: 32, paddingY: 20 } },
    },
    'footer-note': {
      id: 'footer-note',
      type: 'text',
      parentId: 'horizon-footer',
      childIds: [],
      content: { base: { text: 'Horizon · São Miguel, Azores · No concierge, just a key and a map. hello@horizon.house' } },
      style: { base: { fontSize: 12, textAlign: 'center', color: '#9CA3AF' } },
    },
  },
});
