import type { TemplateDoc } from '../types/template';

export const createPortfolioTemplate = (): TemplateDoc => ({
  templateId: 'tpl-portfolio-v1',
  templateName: 'Creative Portfolio',
  revision: 0,
  rootId: 'page-root',
  elements: {
    'page-root': {
      id: 'page-root',
      type: 'section',
      parentId: null,
      childIds: ['site-nav', 'intro-section', 'work-section', 'skills-section', 'contact-section', 'site-footer'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0f172a', color: '#e2e8f0' } },
    },
    'site-nav': {
      id: 'site-nav',
      type: 'nav',
      parentId: 'page-root',
      childIds: [],
      content: {
        base: {
          brand: 'Ava Doe Studio',
          links: [
            { label: 'Work', href: '#work' },
            { label: 'About', href: '#about' },
            { label: 'Contact', href: '#contact' },
          ],
        },
      },
      style: {
        base: { backgroundColor: '#0f172a', color: '#f8fafc', paddingX: 40, paddingY: 20 },
        overrides: { mobile: { paddingX: 16 } },
      },
    },
    'intro-section': {
      id: 'intro-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['intro-eyebrow', 'intro-heading', 'intro-text', 'intro-cta'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0f172a', color: '#f8fafc', paddingX: 64, paddingY: 88 } },
    },
    'intro-eyebrow': {
      id: 'intro-eyebrow',
      type: 'text',
      parentId: 'intro-section',
      childIds: [],
      content: { base: { text: 'Portfolio 2026' } },
      style: { base: { fontSize: 13, fontWeight: 600, textAlign: 'center', color: '#7dd3fc', marginBottom: 10 } },
    },
    'intro-heading': {
      id: 'intro-heading',
      type: 'heading',
      parentId: 'intro-section',
      childIds: [],
      content: { base: { text: 'Designing calm interfaces for busy people.' } },
      style: {
        base: { fontSize: 46, fontWeight: 700, textAlign: 'center', lineHeight: 1.15, marginBottom: 16 },
        overrides: { tablet: { fontSize: 38 }, mobile: { fontSize: 30 } },
      },
    },
    'intro-text': {
      id: 'intro-text',
      type: 'text',
      parentId: 'intro-section',
      childIds: [],
      content: {
        base: { text: 'Independent designer and front-end developer partnering with founders to ship thoughtful products.' },
      },
      style: {
        base: { fontSize: 19, textAlign: 'center', lineHeight: 1.6, marginBottom: 28, color: '#cbd5e1' },
        overrides: { mobile: { fontSize: 16 } },
      },
    },
    'intro-cta': {
      id: 'intro-cta',
      type: 'button',
      parentId: 'intro-section',
      childIds: [],
      content: { base: { label: 'View selected work', href: '#work' } },
      style: {
        base: {
          backgroundColor: '#38bdf8',
          color: '#0f172a',
          fontSize: 16,
          fontWeight: 700,
          paddingX: 26,
          paddingY: 14,
          borderRadius: 8,
        },
      },
    },
    'work-section': {
      id: 'work-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['work-heading', 'project-card-1', 'project-card-2'],
      content: { base: {} },
      style: { base: { backgroundColor: '#1e293b', paddingX: 48, paddingY: 64 } },
    },
    'work-heading': {
      id: 'work-heading',
      type: 'heading',
      parentId: 'work-section',
      childIds: [],
      content: { base: { text: 'Selected work' } },
      style: {
        base: { fontSize: 32, fontWeight: 700, textAlign: 'center', marginBottom: 36, color: '#f8fafc' },
        overrides: { mobile: { fontSize: 26 } },
      },
    },
    'project-card-1': {
      id: 'project-card-1',
      type: 'section',
      parentId: 'work-section',
      childIds: ['project-1-title', 'project-1-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#273449', borderRadius: 14, paddingX: 24, paddingY: 24, widthPercent: 50 },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'project-1-title': {
      id: 'project-1-title',
      type: 'heading',
      parentId: 'project-card-1',
      childIds: [],
      content: { base: { text: 'Ledger — fintech onboarding' } },
      style: { base: { fontSize: 21, fontWeight: 700, marginBottom: 10, color: '#f8fafc' } },
    },
    'project-1-text': {
      id: 'project-1-text',
      type: 'text',
      parentId: 'project-card-1',
      childIds: [],
      content: {
        base: { text: 'Cut account setup from nine steps to four for a Series A banking app. Design system + React build.' },
      },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#cbd5e1' } },
    },
    'project-card-2': {
      id: 'project-card-2',
      type: 'section',
      parentId: 'work-section',
      childIds: ['project-2-title', 'project-2-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#273449', borderRadius: 14, paddingX: 24, paddingY: 24, widthPercent: 50 },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'project-2-title': {
      id: 'project-2-title',
      type: 'heading',
      parentId: 'project-card-2',
      childIds: [],
      content: { base: { text: 'Fieldnote — research tooling' } },
      style: { base: { fontSize: 21, fontWeight: 700, marginBottom: 10, color: '#f8fafc' } },
    },
    'project-2-text': {
      id: 'project-2-text',
      type: 'text',
      parentId: 'project-card-2',
      childIds: [],
      content: {
        base: { text: 'Offline-first notes for field researchers; designed the sync conflicts UX and shipped the web client.' },
      },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#cbd5e1' } },
    },
    'skills-section': {
      id: 'skills-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['skills-heading', 'skills-list'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0f172a', paddingX: 64, paddingY: 52 } },
    },
    'skills-heading': {
      id: 'skills-heading',
      type: 'heading',
      parentId: 'skills-section',
      childIds: [],
      content: { base: { text: 'What I bring to a team' } },
      style: { base: { fontSize: 26, fontWeight: 700, textAlign: 'center', marginBottom: 22, color: '#f8fafc' } },
    },
    'skills-list': {
      id: 'skills-list',
      type: 'list',
      parentId: 'skills-section',
      childIds: [],
      content: {
        base: {
          items: [
            'End-to-end product design, from research to UI',
            'React + TypeScript front-end implementation',
            'Design systems and accessibility audits',
          ],
        },
        overrides: { mobile: { items: ['Product design', 'React development'] } },
      },
      style: {
        base: { fontSize: 16, lineHeight: 1.9, widthPercent: 60, color: '#cbd5e1' },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'contact-section': {
      id: 'contact-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['contact-heading', 'contact-button'],
      content: { base: {} },
      style: { base: { backgroundColor: '#38bdf8', paddingX: 48, paddingY: 64 } },
    },
    'contact-heading': {
      id: 'contact-heading',
      type: 'heading',
      parentId: 'contact-section',
      childIds: [],
      content: { base: { text: 'Have a project in mind?' } },
      style: {
        base: { fontSize: 30, fontWeight: 700, textAlign: 'center', marginBottom: 22, color: '#0f172a' },
        overrides: { mobile: { fontSize: 24 } },
      },
    },
    'contact-button': {
      id: 'contact-button',
      type: 'button',
      parentId: 'contact-section',
      childIds: [],
      content: { base: { label: 'hello@avadoe.studio', href: 'mailto:hello@avadoe.studio' } },
      style: {
        base: {
          backgroundColor: '#0f172a',
          color: '#f8fafc',
          fontSize: 16,
          fontWeight: 600,
          paddingX: 26,
          paddingY: 14,
          borderRadius: 8,
        },
      },
    },
    'site-footer': {
      id: 'site-footer',
      type: 'section',
      parentId: 'page-root',
      childIds: ['footer-note'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0f172a', paddingX: 32, paddingY: 22 } },
    },
    'footer-note': {
      id: 'footer-note',
      type: 'text',
      parentId: 'site-footer',
      childIds: [],
      content: { base: { text: '© 2026 Ava Doe Studio. Built with care.' } },
      style: { base: { fontSize: 13, textAlign: 'center', color: '#94a3b8' } },
    },
  },
});
