import type { TemplateDoc } from '../types/template';

export const createSaasTemplate = (): TemplateDoc => ({
  templateId: 'tpl-saas-v1',
  templateName: 'SaaS Launch',
  revision: 0,
  rootId: 'page-root',
  elements: {
    'page-root': {
      id: 'page-root',
      type: 'section',
      parentId: null,
      childIds: ['app-nav', 'pitch-section', 'capability-section', 'pricing-section', 'quote-section', 'join-section', 'legal-footer'],
      content: { base: {} },
      style: { base: { backgroundColor: '#ffffff', color: '#0f172a' } },
    },
    'app-nav': {
      id: 'app-nav',
      type: 'nav',
      parentId: 'page-root',
      childIds: [],
      content: {
        base: {
          brand: 'Flowline',
          links: [
            { label: 'Product', href: '#product' },
            { label: 'Pricing', href: '#pricing' },
            { label: 'Customers', href: '#customers' },
          ],
        },
      },
      style: {
        base: { backgroundColor: '#ffffff', color: '#0f172a', paddingX: 40, paddingY: 18 },
        overrides: { mobile: { paddingX: 14 } },
      },
    },
    'pitch-section': {
      id: 'pitch-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['pitch-badge', 'pitch-heading', 'pitch-subtext', 'pitch-actions'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#eef2ff', color: '#1e1b4b', paddingX: 64, paddingY: 84, textAlign: 'center' },
        overrides: { mobile: { paddingX: 20, paddingY: 56 } },
      },
    },
    'pitch-badge': {
      id: 'pitch-badge',
      type: 'text',
      parentId: 'pitch-section',
      childIds: [],
      content: { base: { text: 'New — automations 2.0 is live' } },
      style: {
        base: { fontSize: 13, fontWeight: 700, textAlign: 'center', color: '#4f46e5', marginBottom: 12 },
      },
    },
    'pitch-heading': {
      id: 'pitch-heading',
      type: 'heading',
      parentId: 'pitch-section',
      childIds: [],
      content: { base: { text: 'Run your whole back office in one flow' } },
      style: {
        base: { fontSize: 44, fontWeight: 800, textAlign: 'center', lineHeight: 1.12, marginBottom: 16 },
        overrides: { tablet: { fontSize: 36 }, mobile: { fontSize: 28 } },
      },
    },
    'pitch-subtext': {
      id: 'pitch-subtext',
      type: 'text',
      parentId: 'pitch-section',
      childIds: [],
      content: {
        base: { text: 'Flowline connects billing, approvals and reporting so small teams stop stitching tools together.' },
      },
      style: {
        base: { fontSize: 19, textAlign: 'center', lineHeight: 1.6, marginBottom: 30, color: '#3730a3' },
        overrides: { mobile: { fontSize: 16 } },
      },
    },
    'pitch-actions': {
      id: 'pitch-actions',
      type: 'button',
      parentId: 'pitch-section',
      childIds: [],
      content: { base: { label: 'Start 14-day trial', href: '#trial' } },
      style: {
        base: {
          backgroundColor: '#4f46e5',
          color: '#ffffff',
          fontSize: 17,
          fontWeight: 700,
          paddingX: 30,
          paddingY: 15,
          borderRadius: 10,
        },
      },
    },
    'capability-section': {
      id: 'capability-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['capability-heading', 'capability-card-1', 'capability-card-2', 'capability-card-3'],
      content: { base: {} },
      style: { base: { backgroundColor: '#ffffff', paddingX: 48, paddingY: 60 } },
    },
    'capability-heading': {
      id: 'capability-heading',
      type: 'heading',
      parentId: 'capability-section',
      childIds: [],
      content: { base: { text: 'Everything after the sale, handled' } },
      style: {
        base: { fontSize: 32, fontWeight: 800, textAlign: 'center', marginBottom: 38, color: '#0f172a' },
        overrides: { mobile: { fontSize: 25 } },
      },
    },
    'capability-card-1': {
      id: 'capability-card-1',
      type: 'section',
      parentId: 'capability-section',
      childIds: ['capability-1-title', 'capability-1-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#f8fafc', borderRadius: 12, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'capability-1-title': {
      id: 'capability-1-title',
      type: 'heading',
      parentId: 'capability-card-1',
      childIds: [],
      content: { base: { text: 'Automated invoicing' } },
      style: { base: { fontSize: 19, fontWeight: 700, marginBottom: 10, color: '#0f172a' } },
    },
    'capability-1-text': {
      id: 'capability-1-text',
      type: 'text',
      parentId: 'capability-card-1',
      childIds: [],
      content: { base: { text: 'Draft, send and reconcile invoices without leaving the deal record.' } },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#475569' } },
    },
    'capability-card-2': {
      id: 'capability-card-2',
      type: 'section',
      parentId: 'capability-section',
      childIds: ['capability-2-title', 'capability-2-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#f8fafc', borderRadius: 12, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'capability-2-title': {
      id: 'capability-2-title',
      type: 'heading',
      parentId: 'capability-card-2',
      childIds: [],
      content: { base: { text: 'Approval chains' } },
      style: { base: { fontSize: 19, fontWeight: 700, marginBottom: 10, color: '#0f172a' } },
    },
    'capability-2-text': {
      id: 'capability-2-text',
      type: 'text',
      parentId: 'capability-card-2',
      childIds: [],
      content: { base: { text: 'Route discounts and refunds to the right approver with full audit trails.' } },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#475569' } },
    },
    'capability-card-3': {
      id: 'capability-card-3',
      type: 'section',
      parentId: 'capability-section',
      childIds: ['capability-3-title', 'capability-3-text'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#f8fafc', borderRadius: 12, paddingX: 22, paddingY: 22, widthPercent: 33 },
        overrides: { tablet: { widthPercent: 100 }, mobile: { widthPercent: 100 } },
      },
    },
    'capability-3-title': {
      id: 'capability-3-title',
      type: 'heading',
      parentId: 'capability-card-3',
      childIds: [],
      content: { base: { text: 'Live revenue dashboards' } },
      style: { base: { fontSize: 19, fontWeight: 700, marginBottom: 10, color: '#0f172a' } },
    },
    'capability-3-text': {
      id: 'capability-3-text',
      type: 'text',
      parentId: 'capability-card-3',
      childIds: [],
      content: { base: { text: 'MRR, churn and collections updated the moment a payment lands.' } },
      style: { base: { fontSize: 15, lineHeight: 1.6, color: '#475569' } },
    },
    'pricing-section': {
      id: 'pricing-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['pricing-heading', 'plan-starter', 'plan-growth'],
      content: { base: {} },
      style: { base: { backgroundColor: '#f1f5f9', paddingX: 48, paddingY: 64 } },
    },
    'pricing-heading': {
      id: 'pricing-heading',
      type: 'heading',
      parentId: 'pricing-section',
      childIds: [],
      content: { base: { text: 'Simple, seat-free pricing' } },
      style: {
        base: { fontSize: 30, fontWeight: 800, textAlign: 'center', marginBottom: 34, color: '#0f172a' },
        overrides: { mobile: { fontSize: 24 } },
      },
    },
    'plan-starter': {
      id: 'plan-starter',
      type: 'section',
      parentId: 'pricing-section',
      childIds: ['plan-starter-name', 'plan-starter-price', 'plan-starter-includes'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#ffffff', borderRadius: 14, paddingX: 26, paddingY: 26, widthPercent: 50 },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'plan-starter-name': {
      id: 'plan-starter-name',
      type: 'heading',
      parentId: 'plan-starter',
      childIds: [],
      content: { base: { text: 'Starter' } },
      style: { base: { fontSize: 18, fontWeight: 700, marginBottom: 6, color: '#0f172a' } },
    },
    'plan-starter-price': {
      id: 'plan-starter-price',
      type: 'text',
      parentId: 'plan-starter',
      childIds: [],
      content: { base: { text: '$29 / month' } },
      style: {
        base: { fontSize: 34, fontWeight: 800, marginBottom: 14, color: '#4f46e5' },
        overrides: { mobile: { fontSize: 28 } },
      },
    },
    'plan-starter-includes': {
      id: 'plan-starter-includes',
      type: 'list',
      parentId: 'plan-starter',
      childIds: [],
      content: {
        base: {
          items: ['Up to 50 active deals', 'Automated invoicing', 'Email support'],
        },
      },
      style: { base: { fontSize: 15, lineHeight: 1.9, color: '#475569' } },
    },
    'plan-growth': {
      id: 'plan-growth',
      type: 'section',
      parentId: 'pricing-section',
      childIds: ['plan-growth-name', 'plan-growth-price', 'plan-growth-includes'],
      content: { base: {} },
      style: {
        base: { backgroundColor: '#1e1b4b', borderRadius: 14, paddingX: 26, paddingY: 26, widthPercent: 50, color: '#e0e7ff' },
        overrides: { mobile: { widthPercent: 100 } },
      },
    },
    'plan-growth-name': {
      id: 'plan-growth-name',
      type: 'heading',
      parentId: 'plan-growth',
      childIds: [],
      content: { base: { text: 'Growth' } },
      style: { base: { fontSize: 18, fontWeight: 700, marginBottom: 6, color: '#ffffff' } },
    },
    'plan-growth-price': {
      id: 'plan-growth-price',
      type: 'text',
      parentId: 'plan-growth',
      childIds: [],
      content: { base: { text: '$79 / month' } },
      style: {
        base: { fontSize: 34, fontWeight: 800, marginBottom: 14, color: '#a5b4fc' },
        overrides: { mobile: { fontSize: 28 } },
      },
    },
    'plan-growth-includes': {
      id: 'plan-growth-includes',
      type: 'list',
      parentId: 'plan-growth',
      childIds: [],
      content: {
        base: {
          items: ['Unlimited deals', 'Approval chains + audit log', 'Priority support & onboarding'],
        },
      },
      style: { base: { fontSize: 15, lineHeight: 1.9, color: '#c7d2fe' } },
    },
    'quote-section': {
      id: 'quote-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['customer-quote', 'customer-attribution'],
      content: { base: {} },
      style: { base: { backgroundColor: '#ffffff', paddingX: 72, paddingY: 52 } },
    },
    'customer-quote': {
      id: 'customer-quote',
      type: 'text',
      parentId: 'quote-section',
      childIds: [],
      content: {
        base: { text: '“We replaced four subscriptions with Flowline and closed the quarter two weeks early.”' },
      },
      style: {
        base: { fontSize: 21, textAlign: 'center', lineHeight: 1.55, marginBottom: 10, color: '#0f172a' },
        overrides: { mobile: { fontSize: 17 } },
      },
    },
    'customer-attribution': {
      id: 'customer-attribution',
      type: 'text',
      parentId: 'quote-section',
      childIds: [],
      content: { base: { text: '— Priya Nair, COO at Brightseed' } },
      style: { base: { fontSize: 14, fontWeight: 600, textAlign: 'center', color: '#64748b' } },
    },
    'join-section': {
      id: 'join-section',
      type: 'section',
      parentId: 'page-root',
      childIds: ['join-heading', 'join-button'],
      content: { base: {} },
      style: { base: { backgroundColor: '#4f46e5', paddingX: 48, paddingY: 66 } },
    },
    'join-heading': {
      id: 'join-heading',
      type: 'heading',
      parentId: 'join-section',
      childIds: [],
      content: { base: { text: 'Bring order to your back office' } },
      style: {
        base: { fontSize: 30, fontWeight: 800, textAlign: 'center', marginBottom: 22, color: '#ffffff' },
        overrides: { mobile: { fontSize: 23 } },
      },
    },
    'join-button': {
      id: 'join-button',
      type: 'button',
      parentId: 'join-section',
      childIds: [],
      content: { base: { label: 'Start free trial', href: '#trial' } },
      style: {
        base: {
          backgroundColor: '#ffffff',
          color: '#4f46e5',
          fontSize: 16,
          fontWeight: 700,
          paddingX: 28,
          paddingY: 14,
          borderRadius: 10,
        },
      },
    },
    'legal-footer': {
      id: 'legal-footer',
      type: 'section',
      parentId: 'page-root',
      childIds: ['legal-text'],
      content: { base: {} },
      style: { base: { backgroundColor: '#0f172a', paddingX: 32, paddingY: 20 } },
    },
    'legal-text': {
      id: 'legal-text',
      type: 'text',
      parentId: 'legal-footer',
      childIds: [],
      content: { base: { text: '© 2026 Flowline Inc. Privacy · Terms · Status' } },
      style: { base: { fontSize: 13, textAlign: 'center', color: '#94a3b8' } },
    },
  },
});
